apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: {{ include "agent-sandbox.warmpoolName" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  sandboxTemplateRef:
    name: {{ include "agent-sandbox.templateName" . }}
 